apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-apps
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{"example-apps-{{name}}"}}'
      labels:
        applications-management.local.co/app-name: example_apps
    spec:
      destination:
        namespace: master
        server: '{{"{{server}}"}}'
      project: default
      revisionHistoryLimit: 1
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: {{ .Values.example_apps.targetRevision }}
        path: guestbook
